### ISSUE TITLE
FileNotFound Error when running DialignOffline on Windows

### ISSUE THREAD

**Issue by KonstSkouras** [GuillaumeDD/dialign#2]
Hi,

I tried to run the dialign offline on Windows with the example corpus, but I got a FileNotFoundError when it tried to write the first lexicon.tsv in the output dir.

I noticed that it uses as a dialog name the full input dialog path, which causes the problem when it appends the whole path in the output lexicon file name. 

After some digging in the code, the issue seems to be at **line 183 of the IO/DialogueReader class where it uses "/" to split the path, while for Windows the splitting character should be "\\\\"**. 

So, after replacing 
`val name = filename.split("/").last.replaceAll("\\.", "_")`
with
`val name = filename.split("\\\\").last.replaceAll("\\.", "_")`
and recompiling it seems to be working fine.

Just mentioning this in case you want to apply a more generic fix, ie checking the OS before doing the split, or doing both splits etc.

**Comment by GuillaumeDD** [comment]
Hi Konstantinos,

Thank you for your feedback! I am going to look into it to provide a fix.

**Comment by GuillaumeDD** [comment]
@KonstSkouras , I think the problem is solved in branch [`fix_windows_path`](https://github.com/GuillaumeDD/dialign/tree/fix_windows_path). However, I do not happen to have a machine running Windows :innocent: . Would you mind giving a try to the new version of `dialign` and tell me if it solves the problem? 

The corrected JAR files:

:star2:  [dialign-1.1.zip](https://github.com/GuillaumeDD/dialign/files/8933477/dialign-1.1.zip)

**Comment by GuillaumeDD** [comment]
Tests on a windows machine ran successfully. Thank you for notifiing the problem!
